import React from 'react';
import { View, Text, ScrollView, Pressable, Share } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from './src/navigation/types';
import { CalculationRecord } from './src/state/calculatorStore';
import Svg, { Path, Circle, Line } from 'react-native-svg';

type ResultsRouteProp = RouteProp<RootStackParamList, 'Results'>;
type NavigationProp = NativeStackNavigationProp<RootStackParamList, 'Results'>;

export default function ResultsScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<NavigationProp>();
  const route = useRoute<ResultsRouteProp>();
  const { calculation } = route.params;

  const handleShare = async () => {
    const { inputs, results } = calculation;
    const message = `Camber Calculator Results
Project: ${calculation.projectName || 'Unnamed'}

INPUTS:
• Member Type: ${inputs.memberType}
• Span: ${inputs.span} ft
• Concrete Strength: ${inputs.concreteStrength} psi
• Moment of Inertia: ${inputs.momentOfInertia.toFixed(0)} in⁴
• Dead Load: ${inputs.deadLoad} lb/ft
${inputs.liveLoad ? `• Live Load: ${inputs.liveLoad} lb/ft` : ''}
• Method: ${inputs.calculationMethod.toUpperCase()}

RESULTS:
• Recommended Camber: ${results.recommendedCamber.toFixed(3)} in
• Initial Camber: ${results.initialCamber.toFixed(3)} in
• Dead Load Deflection: ${results.deadLoadDeflection.toFixed(3)} in
${results.liveLoadDeflection ? `• Live Load Deflection: ${results.liveLoadDeflection.toFixed(3)} in` : ''}
• Long-Term Deflection: ${results.longTermDeflection.toFixed(3)} in
• Final Camber: ${results.finalCamber.toFixed(3)} in
• Modulus of Elasticity: ${(results.modulusOfElasticity / 1000000).toFixed(2)} x 10⁶ psi

Generated by Camber Calculator`;

    try {
      await Share.share({ message });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <View className="flex-1 bg-gray-50">
      <ScrollView
        className="flex-1"
        contentContainerStyle={{ paddingBottom: insets.bottom + 20 }}
      >
        <View className="p-5">
          {/* Header */}
          <View className="mb-6">
            <View className="flex-row items-center justify-between mb-2">
              <Text className="text-3xl font-bold text-gray-900">Results</Text>
              <Pressable
                onPress={handleShare}
                className="bg-blue-500 rounded-full p-2.5"
              >
                <Ionicons name="share-outline" size={20} color="white" />
              </Pressable>
            </View>
            {calculation.projectName && (
              <Text className="text-base text-gray-600">
                {calculation.projectName}
              </Text>
            )}
          </View>

          {/* Visual Representation */}
          <View className="bg-white rounded-xl p-4 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Camber Profile
            </Text>
            <CamberDiagram calculation={calculation} />
          </View>

          {/* Key Results */}
          <View className="bg-gradient-to-r from-blue-500 to-blue-600 rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-white text-sm font-semibold mb-3">
              RECOMMENDED CAMBER
            </Text>
            <Text className="text-white text-5xl font-bold mb-2">
              {calculation.results.recommendedCamber.toFixed(3)}
            </Text>
            <Text className="text-blue-100 text-base">inches</Text>
          </View>

          {/* Detailed Results */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Detailed Results
            </Text>
            
            <ResultRow
              label="Initial Camber"
              value={calculation.results.initialCamber.toFixed(3)}
              unit="in"
              icon="arrow-up-circle"
            />
            <ResultRow
              label="Dead Load Deflection"
              value={calculation.results.deadLoadDeflection.toFixed(3)}
              unit="in"
              icon="arrow-down-circle"
            />
            {calculation.results.liveLoadDeflection && (
              <ResultRow
                label="Live Load Deflection"
                value={calculation.results.liveLoadDeflection.toFixed(3)}
                unit="in"
                icon="arrow-down-circle"
              />
            )}
            <ResultRow
              label="Long-Term Deflection"
              value={calculation.results.longTermDeflection.toFixed(3)}
              unit="in"
              icon="time"
            />
            <ResultRow
              label="Final Camber"
              value={calculation.results.finalCamber.toFixed(3)}
              unit="in"
              icon="analytics"
              isLast
            />
          </View>

          {/* Material Properties */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Material Properties
            </Text>
            
            <ResultRow
              label="Modulus of Elasticity"
              value={(calculation.results.modulusOfElasticity / 1000000).toFixed(2)}
              unit="× 10⁶ psi"
              icon="cube"
            />
            <ResultRow
              label="Creep Factor"
              value={calculation.results.creepFactor.toFixed(2)}
              unit=""
              icon="hourglass"
            />
            <ResultRow
              label="Shrinkage Factor"
              value={calculation.results.shrinkageFactor.toFixed(2)}
              unit=""
              icon="contract"
              isLast
            />
          </View>

          {/* Input Summary */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Input Summary
            </Text>
            
            <InputRow label="Member Type" value={calculation.inputs.memberType} />
            <InputRow label="Span" value={`${calculation.inputs.span} ft`} />
            <InputRow
              label="Concrete Strength"
              value={`${calculation.inputs.concreteStrength} psi`}
            />
            <InputRow
              label="Moment of Inertia"
              value={`${calculation.inputs.momentOfInertia.toFixed(0)} in⁴`}
            />
            <InputRow
              label="Dead Load"
              value={`${calculation.inputs.deadLoad} lb/ft`}
            />
            {calculation.inputs.liveLoad && (
              <InputRow
                label="Live Load"
                value={`${calculation.inputs.liveLoad} lb/ft`}
              />
            )}
            <InputRow
              label="Method"
              value={calculation.inputs.calculationMethod.toUpperCase()}
              isLast
            />
          </View>

          {/* Action Buttons */}
          <Pressable
            onPress={() => navigation.navigate('Calculator')}
            className="bg-blue-500 rounded-xl py-4 items-center active:bg-blue-600 mb-3"
          >
            <Text className="text-white text-base font-semibold">
              New Calculation
            </Text>
          </Pressable>

          <Pressable
            onPress={() => navigation.navigate('History')}
            className="bg-white border border-gray-300 rounded-xl py-4 items-center active:bg-gray-50"
          >
            <Text className="text-gray-700 text-base font-semibold">
              View History
            </Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  );
}

interface ResultRowProps {
  label: string;
  value: string;
  unit: string;
  icon: keyof typeof Ionicons.glyphMap;
  isLast?: boolean;
}

function ResultRow({ label, value, unit, icon, isLast }: ResultRowProps) {
  return (
    <View
      className={`flex-row items-center justify-between py-3 ${
        !isLast ? 'border-b border-gray-100' : ''
      }`}
    >
      <View className="flex-row items-center flex-1">
        <View className="bg-gray-100 rounded-full p-2 mr-3">
          <Ionicons name={icon} size={18} color="#4B5563" />
        </View>
        <Text className="text-sm text-gray-700">{label}</Text>
      </View>
      <Text className="text-base font-semibold text-gray-900">
        {value} <Text className="text-sm text-gray-600">{unit}</Text>
      </Text>
    </View>
  );
}

interface InputRowProps {
  label: string;
  value: string;
  isLast?: boolean;
}

function InputRow({ label, value, isLast }: InputRowProps) {
  return (
    <View
      className={`flex-row justify-between py-3 ${
        !isLast ? 'border-b border-gray-100' : ''
      }`}
    >
      <Text className="text-sm text-gray-600">{label}</Text>
      <Text className="text-sm font-medium text-gray-900">{value}</Text>
    </View>
  );
}

interface CamberDiagramProps {
  calculation: CalculationRecord;
}

function CamberDiagram({ calculation }: CamberDiagramProps) {
  const width = 320;
  const height = 180;
  const padding = 20;
  const beamLength = width - 2 * padding;
  const centerY = height / 2;

  const { initialCamber, deadLoadDeflection, finalCamber } = calculation.results;
  
  // Scale factor for visual representation
  const maxDeflection = Math.max(Math.abs(initialCamber), Math.abs(finalCamber), Math.abs(deadLoadDeflection));
  const scale = maxDeflection > 0 ? 30 / maxDeflection : 1;

  // Calculate y positions (negative is up)
  const initialCamberY = centerY - (initialCamber * scale);
  const finalCamberY = centerY - (finalCamber * scale);

  // Create curved path for camber using quadratic bezier
  const createCamberPath = (camberY: number) => {
    const controlY = camberY;
    return `M ${padding} ${centerY} Q ${padding + beamLength / 2} ${controlY} ${padding + beamLength} ${centerY}`;
  };

  return (
    <View>
      <Svg width={width} height={height}>
        {/* Reference line (straight) */}
        <Line
          x1={padding}
          y1={centerY}
          x2={padding + beamLength}
          y2={centerY}
          stroke="#D1D5DB"
          strokeWidth="1"
          strokeDasharray="4,4"
        />

        {/* Initial camber (upward curve) */}
        <Path
          d={createCamberPath(initialCamberY)}
          stroke="#3B82F6"
          strokeWidth="2"
          fill="none"
        />

        {/* Final camber (slight upward curve) */}
        {finalCamber > 0 && (
          <Path
            d={createCamberPath(finalCamberY)}
            stroke="#10B981"
            strokeWidth="2"
            fill="none"
            strokeDasharray="4,4"
          />
        )}

        {/* Support points */}
        <Circle cx={padding} cy={centerY} r="4" fill="#6B7280" />
        <Circle cx={padding + beamLength} cy={centerY} r="4" fill="#6B7280" />

        {/* Dimension arrows and labels */}
        <Line
          x1={padding + beamLength / 2}
          y1={centerY}
          x2={padding + beamLength / 2}
          y2={initialCamberY}
          stroke="#3B82F6"
          strokeWidth="1"
        />
        <Circle cx={padding + beamLength / 2} cy={initialCamberY} r="3" fill="#3B82F6" />
      </Svg>

      {/* Legend */}
      <View className="mt-4 space-y-2">
        <View className="flex-row items-center">
          <View className="w-8 h-0.5 bg-blue-500 mr-2" />
          <Text className="text-xs text-gray-600">Initial Camber (at release)</Text>
        </View>
        {finalCamber > 0 && (
          <View className="flex-row items-center">
            <View className="w-8 border-b border-dashed border-green-500 mr-2" />
            <Text className="text-xs text-gray-600">Final Camber (long-term)</Text>
          </View>
        )}
        <View className="flex-row items-center">
          <View className="w-8 border-b border-dashed border-gray-400 mr-2" />
          <Text className="text-xs text-gray-600">Reference (no camber)</Text>
        </View>
      </View>
    </View>
  );
}
