import React, { useState } from 'react';
import { View, Text, ScrollView, Pressable, Share, TextInput } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/types';
import { CalculationRecord, useCalculatorStore } from '../state/calculatorStore';
import Svg, { Path, Circle, Line } from 'react-native-svg';
import { getStrandPattern } from '../utils/strand-patterns';
import { formatInchesWithFraction, decimalToFraction, parseMeasurementInput } from '../utils/cn';

type ResultsRouteProp = RouteProp<RootStackParamList, 'Results'>;
type NavigationProp = NativeStackNavigationProp<RootStackParamList, 'Results'>;

export default function ResultsScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<NavigationProp>();
  const route = useRoute<ResultsRouteProp>();
  const { calculation } = route.params;
  const { updateCalculation } = useCalculatorStore();
  
  const [actualMeasured, setActualMeasured] = useState(
    calculation.actualMeasuredCamber?.toString() || ''
  );

  const handleSaveMeasurement = () => {
    const measured = parseMeasurementInput(actualMeasured);
    if (measured !== null && measured > 0) {
      // Compare actual measured to the calculated camber at release (netInitialCamber)
      const variance = measured - calculation.results.netInitialCamber;
      updateCalculation(calculation.id, {
        actualMeasuredCamber: measured,
        variance: variance,
        measurementDate: Date.now(),
      });
    }
  };

  const variance = calculation.variance !== undefined 
    ? calculation.variance 
    : calculation.actualMeasuredCamber !== undefined
      ? calculation.actualMeasuredCamber - calculation.results.netInitialCamber
      : undefined;

  const handleShare = async () => {
    const { inputs, results } = calculation;
    const message = `Camber Calculator Results
Project: ${calculation.projectName || 'Unnamed'}

INPUTS:
• Member Type: ${inputs.memberType}
• Span: ${inputs.span.toFixed(3)} ft
• Release Strength (f'ci): ${inputs.releaseStrength} psi
• 28-Day Strength (f'c): ${inputs.concreteStrength} psi
• Moment of Inertia: ${inputs.momentOfInertia.toFixed(0)} in⁴
• Dead Load: ${inputs.deadLoad} lb/ft
${inputs.liveLoad ? `• Live Load: ${inputs.liveLoad} lb/ft` : ''}

RESULTS:
• Recommended Camber: ${formatInchesWithFraction(results.recommendedCamber)}
• Calculated Camber at Release: ${formatInchesWithFraction(results.netInitialCamber)}
  (Prestress: ${formatInchesWithFraction(results.initialCamber)} - Dead Load: ${formatInchesWithFraction(results.deadLoadDeflection)})
${results.liveLoadDeflection ? `• Live Load Deflection: ${formatInchesWithFraction(results.liveLoadDeflection)}` : ''}
• Long-Term Deflection: ${formatInchesWithFraction(results.longTermDeflection)}
• Final Camber: ${formatInchesWithFraction(results.finalCamber)}
• Ec at Release: ${(results.releaseModulusOfElasticity / 1000000).toFixed(2)} x 10⁶ psi
• Ec at 28 Days: ${(results.modulusOfElasticity / 1000000).toFixed(2)} x 10⁶ psi

Generated by Camber Calculator`;

    try {
      await Share.share({ message });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <View className="flex-1 bg-gray-50">
      <ScrollView
        className="flex-1"
        contentContainerStyle={{ paddingBottom: insets.bottom + 20 }}
      >
        <View className="p-5">
          {/* Header */}
          <View className="mb-6">
            <View className="flex-row items-center justify-between mb-2">
              <Text className="text-3xl font-bold text-gray-900">Results</Text>
              <Pressable
                onPress={handleShare}
                className="bg-blue-500 rounded-full p-2.5"
              >
                <Ionicons name="share-outline" size={20} color="white" />
              </Pressable>
            </View>
            {calculation.projectName && (
              <Text className="text-base text-gray-600">
                {calculation.projectName}
              </Text>
            )}
          </View>

          {/* Visual Representation */}
          <View className="bg-white rounded-xl p-4 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Camber Profile
            </Text>
            <CamberDiagram calculation={calculation} />
          </View>

          {/* Key Results */}
          <View className="bg-gradient-to-r from-blue-500 to-blue-600 rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-white text-sm font-semibold mb-3">
              RECOMMENDED CAMBER
            </Text>
            <Text className="text-white text-5xl font-bold mb-2">
              {calculation.results.recommendedCamber.toFixed(3)}
            </Text>
            <Text className="text-blue-100 text-base">
              inches (≈{decimalToFraction(calculation.results.recommendedCamber)})
            </Text>
          </View>

          {/* Actual Measured Camber Section */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <View className="flex-row items-center mb-4">
              <Ionicons name="resize" size={20} color="#3B82F6" />
              <Text className="text-lg font-semibold text-gray-900 ml-2">
                Measured Camber at Release
              </Text>
            </View>
            
            <Text className="text-sm text-gray-600 mb-3">
              Enter the actual measured camber from the field at release:
            </Text>
            
            <View className="flex-row gap-3 mb-3">
              <View className="flex-1">
                <TextInput
                  className="bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-base text-gray-900"
                  placeholder='e.g., 0.6875 or 11/16'
                  placeholderTextColor="#9CA3AF"
                  cursorColor="#000000"
                  value={actualMeasured}
                  onChangeText={setActualMeasured}
                />
                <Text className="text-xs text-gray-500 mt-1 px-1">
                  Accepts decimal (0.6875) or fraction (11/16 or 1 5/16)
                </Text>
              </View>
              <Pressable
                onPress={handleSaveMeasurement}
                className="bg-blue-500 rounded-xl px-6 py-3 justify-center active:bg-blue-600"
              >
                <Text className="text-white font-semibold">Save</Text>
              </Pressable>
            </View>

            {calculation.actualMeasuredCamber !== undefined && variance !== undefined && (
              <View className="bg-gray-50 rounded-lg p-3">
                <View className="flex-row justify-between mb-2">
                  <Text className="text-sm text-gray-700">Measured:</Text>
                  <Text className="text-sm font-semibold text-gray-900">
                    {formatInchesWithFraction(calculation.actualMeasuredCamber)}
                  </Text>
                </View>
                <View className="flex-row justify-between mb-2">
                  <Text className="text-sm text-gray-700">Calculated at Release:</Text>
                  <Text className="text-sm font-semibold text-gray-900">
                    {formatInchesWithFraction(calculation.results.netInitialCamber)}
                  </Text>
                </View>
                <View className="border-t border-gray-300 my-2" />
                <View className="flex-row justify-between">
                  <Text className="text-sm font-bold text-gray-900">Variance:</Text>
                  <Text className={`text-sm font-bold ${variance >= 0 ? 'text-blue-600' : 'text-orange-600'}`}>
                    {variance >= 0 ? '+' : ''}{variance.toFixed(3)}" ({variance >= 0 ? '+' : ''}{decimalToFraction(Math.abs(variance))})
                  </Text>
                </View>
                <View className="mt-3 bg-yellow-50 border border-yellow-200 rounded-lg p-2">
                  <Text className="text-xs text-yellow-800 text-center">
                    ⚠️ Tolerance checking coming soon
                  </Text>
                </View>
              </View>
            )}
          </View>

          {/* Detailed Results */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Detailed Results
            </Text>
            
            {/* Calculated Camber at Release - HIGHLIGHTED */}
            <View className="bg-blue-50 rounded-lg p-3 mb-3 border-2 border-blue-200">
              <View className="flex-row items-center justify-between">
                <View className="flex-row items-center flex-1">
                  <View className="bg-blue-500 rounded-full p-2 mr-3">
                    <Ionicons name="trending-up" size={18} color="white" />
                  </View>
                  <View className="flex-1">
                    <Text className="text-sm font-bold text-blue-900">
                      Calculated Camber at Release
                    </Text>
                    <Text className="text-xs text-blue-700 mt-0.5">
                      Expected field measurement after stripping
                    </Text>
                  </View>
                </View>
                <View className="items-end">
                  <Text className="text-lg font-bold text-blue-900">
                    {formatInchesWithFraction(calculation.results.netInitialCamber)}
                  </Text>
                </View>
              </View>
            </View>

            {/* Breakdown Section */}
            <View className="bg-gray-50 rounded-lg p-3 mb-3">
              <Text className="text-xs font-semibold text-gray-700 mb-2">Breakdown:</Text>
              <View className="flex-row justify-between items-center mb-1">
                <Text className="text-xs text-gray-600">• Prestress Camber (built-in)</Text>
                <Text className="text-xs font-medium text-gray-900">
                  {formatInchesWithFraction(calculation.results.initialCamber)}
                </Text>
              </View>
              <View className="flex-row justify-between items-center mb-1">
                <Text className="text-xs text-gray-600">• Dead Load Deflection</Text>
                <Text className="text-xs font-medium text-red-600">
                  -{formatInchesWithFraction(calculation.results.deadLoadDeflection)}
                </Text>
              </View>
              <View className="border-t border-gray-300 my-1" />
              <View className="flex-row justify-between items-center">
                <Text className="text-xs font-semibold text-gray-900">= Net Camber Measurement</Text>
                <Text className="text-xs font-bold text-blue-900">
                  {formatInchesWithFraction(calculation.results.netInitialCamber)}
                </Text>
              </View>
            </View>

            {calculation.results.liveLoadDeflection && (
              <ResultRow
                label="Live Load Deflection"
                value={calculation.results.liveLoadDeflection}
                unit="in"
                icon="arrow-down-circle"
                showFraction={true}
              />
            )}
            <ResultRow
              label="Long-Term Deflection"
              value={calculation.results.longTermDeflection}
              unit="in"
              icon="time"
              showFraction={true}
            />
            <ResultRow
              label="Final Camber"
              value={calculation.results.finalCamber}
              unit="in"
              icon="analytics"
              showFraction={true}
              isLast
            />
          </View>

          {/* Material Properties */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Material Properties
            </Text>
            
            <ResultRow
              label="Ec at Release"
              value={(calculation.results.releaseModulusOfElasticity / 1000000).toFixed(2)}
              unit="× 10⁶ psi"
              icon="flash"
            />
            <ResultRow
              label="Ec at 28 Days"
              value={(calculation.results.modulusOfElasticity / 1000000).toFixed(2)}
              unit="× 10⁶ psi"
              icon="cube"
            />
            <ResultRow
              label="Creep Factor"
              value={calculation.results.creepFactor.toFixed(2)}
              unit=""
              icon="hourglass"
            />
            <ResultRow
              label="Shrinkage Factor"
              value={calculation.results.shrinkageFactor.toFixed(2)}
              unit=""
              icon="contract"
              isLast
            />
          </View>

          {/* Input Summary */}
          <View className="bg-white rounded-xl p-5 mb-5 shadow-sm">
            <Text className="text-lg font-semibold text-gray-900 mb-4">
              Input Summary
            </Text>
            
            {calculation.inputs.projectNumber && (
              <InputRow label="Project #" value={calculation.inputs.projectNumber} />
            )}
            {calculation.inputs.markNumber && (
              <InputRow label="Mark #" value={calculation.inputs.markNumber} />
            )}
            {calculation.inputs.idNumber && (
              <InputRow label="ID #" value={calculation.inputs.idNumber} />
            )}
            <InputRow label="Member Type" value={calculation.inputs.memberType} />
            <InputRow label="Span" value={`${calculation.inputs.span.toFixed(3)} ft`} />
            <InputRow
              label="Release Strength (f'ci)"
              value={`${calculation.inputs.releaseStrength} psi`}
            />
            <InputRow
              label="28-Day Strength (f'c)"
              value={`${calculation.inputs.concreteStrength} psi`}
            />
            <InputRow
              label="Moment of Inertia"
              value={`${calculation.inputs.momentOfInertia.toFixed(0)} in⁴`}
            />
            <InputRow
              label="Dead Load"
              value={`${calculation.inputs.deadLoad} lb/ft`}
            />
            {calculation.inputs.liveLoad && (
              <InputRow
                label="Live Load"
                value={`${calculation.inputs.liveLoad} lb/ft`}
              />
            )}
            {calculation.inputs.strandPattern && getStrandPattern(calculation.inputs.strandPattern) && (
              <>
                <InputRow
                  label="Strand Pattern"
                  value={getStrandPattern(calculation.inputs.strandPattern)?.name || ''}
                />
                <InputRow
                  label="e value"
                  value={`${calculation.inputs.strandEValue}" from bottom`}
                />
              </>
            )}
            {calculation.inputs.topStrandPattern && getStrandPattern(calculation.inputs.topStrandPattern) && (
              <>
                <InputRow
                  label="Top Strand Pattern"
                  value={getStrandPattern(calculation.inputs.topStrandPattern)?.name || ''}
                  isLast
                />
              </>
            )}
            {!calculation.inputs.topStrandPattern && (
              <View style={{ height: 0 }} />
            )}
          </View>

          {/* Action Buttons */}
          <Pressable
            onPress={() => navigation.navigate('Calculator', { editingCalculation: calculation })}
            className="bg-orange-500 rounded-xl py-4 items-center active:bg-orange-600 mb-3"
          >
            <Text className="text-white text-base font-semibold">
              Edit Calculation
            </Text>
          </Pressable>

          <Pressable
            onPress={() => navigation.navigate('Calculator')}
            className="bg-blue-500 rounded-xl py-4 items-center active:bg-blue-600 mb-3"
          >
            <Text className="text-white text-base font-semibold">
              New Calculation
            </Text>
          </Pressable>

          <Pressable
            onPress={() => navigation.navigate('History')}
            className="bg-white border border-gray-300 rounded-xl py-4 items-center active:bg-gray-50"
          >
            <Text className="text-gray-700 text-base font-semibold">
              View History
            </Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  );
}

interface ResultRowProps {
  label: string;
  value: string | number;
  unit: string;
  icon: keyof typeof Ionicons.glyphMap;
  isLast?: boolean;
  showFraction?: boolean;
}

function ResultRow({ label, value, unit, icon, isLast, showFraction = false }: ResultRowProps) {
  const displayValue = typeof value === 'number' && showFraction 
    ? formatInchesWithFraction(value)
    : typeof value === 'number'
      ? value.toFixed(3)
      : value;

  return (
    <View
      className={`flex-row items-center justify-between py-3 ${
        !isLast ? 'border-b border-gray-100' : ''
      }`}
    >
      <View className="flex-row items-center flex-1">
        <View className="bg-gray-100 rounded-full p-2 mr-3">
          <Ionicons name={icon} size={18} color="#4B5563" />
        </View>
        <Text className="text-sm text-gray-700">{label}</Text>
      </View>
      <Text className="text-base font-semibold text-gray-900">
        {displayValue} <Text className="text-sm text-gray-600">{unit}</Text>
      </Text>
    </View>
  );
}

interface InputRowProps {
  label: string;
  value: string;
  isLast?: boolean;
}

function InputRow({ label, value, isLast }: InputRowProps) {
  return (
    <View
      className={`flex-row justify-between py-3 ${
        !isLast ? 'border-b border-gray-100' : ''
      }`}
    >
      <Text className="text-sm text-gray-600">{label}</Text>
      <Text className="text-sm font-medium text-gray-900">{value}</Text>
    </View>
  );
}

interface CamberDiagramProps {
  calculation: CalculationRecord;
}

function CamberDiagram({ calculation }: CamberDiagramProps) {
  const width = 320;
  const height = 200;
  const padding = 20;
  const beamLength = width - 2 * padding;
  const centerY = height / 2;

  const { netInitialCamber, finalCamber } = calculation.results;
  const { actualMeasuredCamber } = calculation;
  
  // Scale factor for visual representation - include measured camber in scale calculation
  const maxDeflection = Math.max(
    Math.abs(netInitialCamber), 
    Math.abs(finalCamber),
    actualMeasuredCamber ? Math.abs(actualMeasuredCamber) : 0
  );
  const scale = maxDeflection > 0 ? 30 / maxDeflection : 1;

  // Calculate y positions (negative is up)
  const initialCamberY = centerY - (netInitialCamber * scale);
  const finalCamberY = centerY - (finalCamber * scale);
  const measuredCamberY = actualMeasuredCamber ? centerY - (actualMeasuredCamber * scale) : null;

  // Create curved path for camber using quadratic bezier
  const createCamberPath = (camberY: number) => {
    const controlY = camberY;
    return `M ${padding} ${centerY} Q ${padding + beamLength / 2} ${controlY} ${padding + beamLength} ${centerY}`;
  };

  return (
    <View>
      <Svg width={width} height={height}>
        {/* Reference line (straight) */}
        <Line
          x1={padding}
          y1={centerY}
          x2={padding + beamLength}
          y2={centerY}
          stroke="#D1D5DB"
          strokeWidth="1"
          strokeDasharray="4,4"
        />

        {/* Calculated camber curve (blue solid line) */}
        <Path
          d={createCamberPath(initialCamberY)}
          stroke="#3B82F6"
          strokeWidth="2"
          fill="none"
        />

        {/* Measured camber curve (orange solid line) - if available */}
        {measuredCamberY !== null && (
          <Path
            d={createCamberPath(measuredCamberY)}
            stroke="#F97316"
            strokeWidth="2"
            fill="none"
          />
        )}

        {/* Final camber (slight upward curve) */}
        {finalCamber > 0 && (
          <Path
            d={createCamberPath(finalCamberY)}
            stroke="#10B981"
            strokeWidth="2"
            fill="none"
            strokeDasharray="4,4"
          />
        )}

        {/* Support points */}
        <Circle cx={padding} cy={centerY} r="4" fill="#6B7280" />
        <Circle cx={padding + beamLength} cy={centerY} r="4" fill="#6B7280" />

        {/* Dimension line and label for calculated camber */}
        <Line
          x1={padding + beamLength / 2}
          y1={centerY}
          x2={padding + beamLength / 2}
          y2={initialCamberY}
          stroke="#3B82F6"
          strokeWidth="1"
        />
        <Circle cx={padding + beamLength / 2} cy={initialCamberY} r="3" fill="#3B82F6" />

        {/* Dimension line and label for measured camber - if available */}
        {measuredCamberY !== null && (
          <>
            <Line
              x1={padding + beamLength / 2 + 40}
              y1={centerY}
              x2={padding + beamLength / 2 + 40}
              y2={measuredCamberY}
              stroke="#F97316"
              strokeWidth="1"
            />
            <Circle cx={padding + beamLength / 2 + 40} cy={measuredCamberY} r="3" fill="#F97316" />
          </>
        )}
      </Svg>

      {/* Value labels below the SVG */}
      <View className="flex-row justify-center gap-4 mt-2 mb-2">
        <View className="items-center">
          <Text className="text-xs font-semibold text-blue-600">
            {netInitialCamber.toFixed(3)}" (≈{decimalToFraction(netInitialCamber)})
          </Text>
          <Text className="text-xs text-gray-500">Calculated</Text>
        </View>
        {actualMeasuredCamber !== undefined && (
          <View className="items-center">
            <Text className="text-xs font-semibold text-orange-600">
              {actualMeasuredCamber.toFixed(3)}" (≈{decimalToFraction(actualMeasuredCamber)})
            </Text>
            <Text className="text-xs text-gray-500">Measured</Text>
          </View>
        )}
      </View>

      {/* Legend */}
      <View className="mt-2 space-y-2">
        <View className="flex-row items-center">
          <View className="w-8 h-0.5 bg-blue-500 mr-2" />
          <Text className="text-xs text-gray-600">Calculated camber at release</Text>
        </View>
        {actualMeasuredCamber !== undefined && (
          <View className="flex-row items-center">
            <View className="w-8 h-0.5 bg-orange-500 mr-2" />
            <Text className="text-xs text-gray-600">Measured camber at release</Text>
          </View>
        )}
        {finalCamber > 0 && (
          <View className="flex-row items-center">
            <View className="w-8 border-b border-dashed border-green-500 mr-2" />
            <Text className="text-xs text-gray-600">Final camber (long-term)</Text>
          </View>
        )}
        <View className="flex-row items-center">
          <View className="w-8 border-b border-dashed border-gray-400 mr-2" />
          <Text className="text-xs text-gray-600">Reference (no camber)</Text>
        </View>
      </View>
    </View>
  );
}
